http.listener.host: "0.0.0.0"
http.listener.port: "8084"
http.listener.readtimeout: "30000"

http.requester.papi.customer.host: "0.0.0.0"
http.requester.papi.customer.port: "8083"
http.requester.papi.customer.registration.path: "/api/customers"



sfdc.username: "![SXJgsguRZjEvxKP3deKKFrdgSLcXqN4ym1KLxsA+OQk=]"
sfdc.password: "![iKd12Zp2ENrg+SIxwV9auw==]"
sfdc.securityToken: "![SsqVYrechFCAuunn1uOw40Ub9sGELvbMn9+q6hAm8Ec=]"