#%RAML 1.0 DataType

type: object
properties:
  eventinstanceId:
    required: true
    type: string
    example: "dsfhdbfhsbdfhjsb3784t2wfsd"
  status:
    required: true
    type: string
    example: "Success"
      